// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CursorClick(arg1:number,arg2:number):Promise<void>;

export function GetCursorLocation():Promise<string>;

export function GetInstalledApplications():Promise<Array<string>>;

export function Screenshot():Promise<string>;

export function TypeWithKeyboard(arg1:string):Promise<void>;
