// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CursorClick(arg1, arg2) {
  return window['go']['main']['App']['CursorClick'](arg1, arg2);
}

export function GetCursorLocation() {
  return window['go']['main']['App']['GetCursorLocation']();
}

export function GetInstalledApplications() {
  return window['go']['main']['App']['GetInstalledApplications']();
}

export function GetRunningApplications() {
  return window['go']['main']['App']['GetRunningApplications']();
}

export function PressKeyCombo(arg1) {
  return window['go']['main']['App']['PressKeyCombo'](arg1);
}

export function Screenshot() {
  return window['go']['main']['App']['Screenshot']();
}

export function TypeWithKeyboard(arg1) {
  return window['go']['main']['App']['TypeWithKeyboard'](arg1);
}
