// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCursorLocation() {
  return window['go']['main']['App']['GetCursorLocation']();
}

export function MoveCursor(arg1, arg2) {
  return window['go']['main']['App']['MoveCursor'](arg1, arg2);
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}

export function Screenshot() {
  return window['go']['main']['App']['Screenshot']();
}

export function TypeWithKeyboard(arg1) {
  return window['go']['main']['App']['TypeWithKeyboard'](arg1);
}
