// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCursorLocation():Promise<string>;

export function MoveCursor(arg1:number,arg2:number):Promise<void>;

export function Query(arg1:string):Promise<string>;

export function Screenshot():Promise<string>;

export function TypeWithKeyboard(arg1:string):Promise<void>;
