// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BringApplicationToForegroundByPID(arg1:number):Promise<void>;

export function CursorClick(arg1:number,arg2:number):Promise<void>;

export function GetApplicationBoundingBoxByPID(arg1:number):Promise<main.ApplicationBoundingBox>;

export function GetCursorLocation():Promise<string>;

export function GetInstalledApplications():Promise<Array<string>>;

export function GetRunningApplications():Promise<Array<main.RunningApplication>>;

export function PressKeyCombo(arg1:main.KeyCombo):Promise<void>;

export function Screenshot():Promise<string>;

export function ScreenshotByPID(arg1:number):Promise<string>;

export function TypeWithKeyboard(arg1:string):Promise<void>;
